package com.vedantu.account.repository;

import java.util.HashMap;
import java.util.Map;

import org.springframework.stereotype.Component;

import com.vedantu.account.entity.AccountEntity;
import com.vedantu.common.exceptions.InvalidUserSession;

@Component
public class AccountRepositoryImpl implements AccountRepository {

	private static Map<String, AccountEntity> accountMap = new HashMap<String, AccountEntity>();

	static {
		AccountEntity account1 = new AccountEntity();
		account1.setId(1);
		account1.setEmailId("user1@vedantu.com");
		account1.setFirstName("User 1");
		account1.setLastName("Testing 1");
		// sessionId will be generated by a separate user authentication service.
		// Assigning here for simplicity
		account1.setSessionId("abc123");
		accountMap.put("abc123", account1);
	}

	@Override
	public AccountEntity validateUserSession(String sessionId) throws InvalidUserSession {
		if(!accountMap.containsKey(sessionId)){
			throw new InvalidUserSession("The session id is Invalid");
		}
		
		return accountMap.get(sessionId);
	}

}
